name: Test Unity License

on:
  workflow_dispatch: # This allows you to run the workflow manually from the Actions tab

jobs:
  activate-unity:
    name: Test Unity Activation
    runs-on: ubuntu-latest
    steps:
      - name: Activate Unity
        uses: game-ci/unity-activate@v2.0.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
